{% set name = "spglib" %}
{% set version = "1.9.9.18" %}
{% set sha256 = "cbbb8383320b500dc6100b83d5e914a26a97ef8fc97c82d8921b10220e4126cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: 
    - python setup.py install --single-version-externally-managed --record record.txt 

requirements:
  build:
    - python
    - numpy x.x
    - setuptools
    - toolchain
  run:
    - python
    - numpy x.x

test:
  imports:
    - spglib
  commands:
    - cd {{ environ.SRC_DIR }}/test
    - python -m unittest discover -b


about:
  home: https://atztogo.github.io/spglib/
  license: BSD-3-clause
  license_family: BSD
  license_file: {{ environ.RECIPE_DIR }}/COPYING
  summary: 'Space symmetry groups spglib module.'


  description: |
    Spglib is a library for finding and handling crystal symmetries.
  doc_url: https://atztogo.github.io/spglib/
  dev_url: https://github.com/atztogo/spglib

extra:
  recipe-maintainers:
    - jochym
    - atztogo
