{% set name = "spglib" %}
{% set version = "1.11.1.2" %}
{% set sha256 = "d99dab24accd269df65c01febd05cb5dd1094a89d7279f8390871f0432df2b56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/atztogo/spglib/archive/v{{ version }}.tar.gz
  
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - blas 1.1 openblas  # [unix]
    - numpy
    - pip
    - setuptools
  run:
    - python
    - blas 1.1 openblas  # [unix]
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - spglib
  source_files:
    - python/test
  commands:
    - python -m unittest discover -b -s python/test


about:
  home: https://atztogo.github.io/spglib/
  license: BSD-3-clause
  license_family: BSD
  license_file: {{ RECIPE_DIR }}/COPYING
  summary: 'Space symmetry groups spglib module/library.'


  description: |
    Spglib is a library for finding and handling crystal symmetries.
  doc_url: https://atztogo.github.io/spglib/
  dev_url: https://github.com/atztogo/spglib

extra:
  recipe-maintainers:
    - jochym
    - atztogo
