{% set name = "spglib" %}
{% set version = "1.16.1" %}
{% set sha256 = "e90682239e4ef63b492fa4e44f7dbcde2e2fe2e688579d96b01f2730dfdf5b2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/atztogo/spglib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports: spglib  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - numpy
    - pip
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pyyaml
  imports:
    - spglib
  source_files:
    - python/test
  commands:
    - python -m unittest discover -b -s python/test


about:
  home: https://atztogo.github.io/spglib/
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ RECIPE_DIR }}/COPYING
  summary: Space symmetry groups spglib module/library.


  description: |
    Spglib is a library for finding and handling crystal symmetries.
  doc_url: https://atztogo.github.io/spglib/
  dev_url: https://github.com/atztogo/spglib

extra:
  recipe-maintainers:
    - jochym
    - atztogo
