# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=35
    - CONDA_NPY=112  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=36
    - CONDA_NPY=112  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Wk0BtLl31Td+SLc3uLjgzey8rEm+qmg6Z4/ocGrJN3Waqj4j7LSUr2xhOFjMcK0HdSciTlQ7IspMFbmLqqiQamdu8qwado+W80Uu573cj62jquJ49AG8jpQZ5mRhsRo+P/TzGTUnevTK1yN9aDhM8QZgUapeKzApvpE+nJNuvLehFryJX5VSoSPZ9SS/AGZ3CVDqzsZfWK4+3nToeWSsPEc18eNxMxDa7bymbveH4eqnqnljV5N0ZJpso2suTJfALJv+ccu1K7ABqazVJKmpCXNS14Izf/P/LJgAs7WHAl0F4Su8h2wp8V6tyQ1HHuAsgz3amfRl2/gini4fn8Pf/BwvwksO0S6JNhm0gCiDLsTvTTh6+MAWT3ffmwg9H/tqg5HLMqS4eokX7dAwN04yHqDKQoKc6PJb+rdXkWNjwHKJ74eHhtRmbCjWMf1Q1sZQ/EWu15SXIE/PnGT5toa9jsqYnNN6msz1koIVF2MKI3Z+KrVX/enO9zajsTMJK3zdeVvyKdTu55I3s2PQlhY0R2gCKSIYCgPAD7Pb38hihx5JdHCezmGj1Sg/rqFECYHoGPSR/PCwXTP/ekJe/MGSLqG40b/Ypj4uUea7Q+LHkn8SOgqvZyZn4TufRMhXI5SeNFMPhzVCYt476ZrFjRAYsDdVz6gti2oiINPJs7WxlqY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
