appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gVbrCZuSH0LIZwdLMkMQJNZe6DMBAUNQRpGI0dFLqsLmE/g6T8pQeqvEs13xzSg5QL1KelbOKEeKCdS9t39CpfxF3cFfFv+5LHrUSrwJhpS4sqd8Ip/NL18ZH3mgyI+mjj+B2ppb5BjFdcsPQOPxhZO6uNTycn+++fO7sz8sHv+uDi4gOy9U4JGAHORkGhOUyS52oAc9tJ3R4rC7tZ7xUZGZ9GJf9/gcwigWQX2Gx5s8UZRfnPn9sdhtWbzdDMULw/g1g5xrKt3zd4Lo4th7hu9i1BmGWLlZ+pXsfvuP1InLoPjWn0KAezLQOTmzXh7RztTEVz0GNYd00LaD7S3RkX02d+v06MPaa7206BSLSblIlf+8/5S5+vVtC38Si94kkS361lKkyUYUj7GiJLNn/rMunZ1WZla3cG+x75lvTuXg9PzYPdElV9deoRPAPVtfAbknB/JRSEExfzUT4lmBZls9Lube4hZANPTE2ewVvh3BUzh4vs2mtdA1A6rWoHM9pR65Y8N8SsAyNlOfORpukcQj8A0H14BvVA84WXZ3TDtSMOnboO8sScXcI/cpf7vl4boP85kLq/MfKsS8+ua+W9VrOrLLOvG3C/21RbHlOp9DnVZcuP0axWCbC7ODAqEzeRNPzuTGRSEFBptQI4pnNn0h27yL0O2XXXTxdktwcfw=}
provider:
  win: azure
